### ISSUE TITLE
Yaw Pitch Roll FOV for FOLLOW mode

### ISSUE THREAD

**Issue by thenoobi** [mchorse/aperture#22]
Can you add
yaw – camera's yaw.
pitch – camera's pitch.
roll – camera's roll.
fov – camera's Field-Of-View.

for follow mode? 
Because I cant set yaw pitch rol fov for this mode, or maybe I just dont know hot to set?
thanks

**Comment by mchorse** [comment]
Use follow modifier on the idle or path fixture. It works same way as follow fixture (besides follow fixture will be removed in the next update in favor of follow modifier). You can also use translate modifier with follow fixture in order to offset XYZ of follow.

**Comment by thenoobi** [comment]
Thanks a lot, But please dont remove Follow Fixture. 
That still usable

**Comment by mchorse** [comment]
No problem, but sorry, I already removed from the code few weeks ago. In my opinion, it's just gets into the way, and it's also less flexible in comparison to follow modifier.
