### ISSUE TITLE
path improvement

### ISSUE THREAD

**Issue by Celophy** [mchorse/aperture#51]
Will be possible set a custom duration for each single path point? it would be mush easier to use

**Comment by mchorse** [comment]
This feature, per point duration option, was available in Aperture 1.4.1 and below, but it was removed in 1.4.2 as I don’t like maintaining two features that do the same thing. Watch [this](https://youtu.be/6eil_zvv1KI?t=163). 

If you still want to use that per point duration feature, you’d have to use older version.

**Comment by Celophy** [comment]
oh ok, thanks!!!
