### ISSUE TITLE
Cant right-click to select fixtures

### ISSUE THREAD

**Issue by Fennecai** [mchorse/aperture#62]
in the tutorial series, it says to right-click the colored bars at the bottom of the screen to select the fixtures. however, when I right-click those, all that happens is a little red line gets placed, and idk what it does.

i assume this is some sort of bug, or poor documentation possibly.

**Comment by mchorse** [comment]
You probably pressed `I` key which enables interactive mode, press `I` again or click the last button IIRC in the top left icon row.
