### ISSUE TITLE
Option to change keys

### ISSUE THREAD

**Issue by ghost** [mchorse/aperture#73]
Hi! 

Very nice mod. 
I would like to suggest to add the possibility to change keybindings, especially for moving the camera manually. 
Left-handers use PL;' (or PLÖÄ on german keyboards) instead of WASD. 

Have a white and cozy winter! =)

**Comment by mchorse** [comment]
You can change them in Ctrl + 0, Aperture, Flight.

**Comment by Chryfi** [comment]
Also, there is a Keybinds menu.
