### ISSUE TITLE
Thanx but I'm sad to cannot contribute to the project

### ISSUE THREAD

**Issue by Niko300-dev** [mchorse/aperture#75]
Thank you for your response and the push, but I've already fixed the bug on my end by adding an annotation @SideOnly(Side.CLIENT) to recordFrame, and that solved the problem for good. Now, I'm really sad that I couldn't push my changes to Github using IntelliJ; it keeps giving me either a 403 error or it loads indefinitely (ps: I'm using a 2019 version to be compatible with Gradle 2.4). Anyway, it was my very first opportunity to contribute to an open-source project, and now, it's a failure :'(     *[translate from FR to EN by chatGPT]*

**Comment by Chryfi** [comment]
I am sorry that you cannot contribute anymore, I was gone on the days and wanted to fix the open issue now. You will be mentioned in the changelog. The client side annotation is not necessary, it would remove the method on the server side and remove the possibility to use it there, it is better to utilise inheritance. EntityPlayerSP is a subclass of EntityPlayer so it does not matter.

**Comment by Niko300-dev** [comment]
Thanx for your response, I understand that it's a better solution to let this method reachable from the server side but I don't have any XP on the Minecraft mod dev (only server plugins) and I have take a few evening up to 2:00AM to understand finally it was the solution of the problem. A good thing done !
